---
- hosts: all
  gather_facts: no
  vars_files:
     - credential.yaml
  tasks:
     - name: file create
       command: touch /tmp/prapulla.txt
     - debug: msg="my secure variable '{{ tenant_cred }}'"
